language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
install:
    - pip install tox-travis
script: tox
deploy:
    on:
        python: '3.6'
        tags: true
    distributions: 'sdist bdist_wheel'
    provider: pypi
    user: 128technology
    password:
        secure: Z6VNi82YixJP5eIeDh1vaMtnBaSLptfNwsI8Thqxr5pqGEu++eiHV7pik5dC4DLwxZlPhwljPEP+AVpQ2W9SuXN3m4lrinbIgB+u3ZxM5I0zmHu2dFLk1JPQleXL3gSTe7t+hqLyX1q+SMObhwZR/rYkPnE5nDBDhlGBmt/EwJK8gfT/asPh+QyMIFwmh7zlrRMo6m7UaDiVHWOqWy5+Mq2/aoWRjRZWGNTZzSZFcfbpzQSPt72ww3jtaD7Ky1h9HT9GEK5tZ362u+UJY9C+pG7RdizuzCIAj/ZYzoUyYu6oh7WdgdHJd2EICUfNEdOClHidrxJN0x/uQfp8hGRyyvDZ1+2AiAvsg17HAwYDa5mOCpzG3/2MrDgSZCDRtwCnWJAyiUhas9CKvgMiJ72wGkAry6wKpUMvzjG2QbG79EjhJdPwV+rLDJvEvy2nOAvdWuWqm7jQHx9SID7/c/t0FgNEbZhWJau3BQfXS7H2F+3EOz+qA+fbSihhJdI1wE2rfMg8tmw0CGBRq9IrChjI4Q+kZjYHzzCArvUuAN6knBv6Qk1ltljkSlScnwNBL37IXkZmuTX8MBipZokpiPRCjYYLUIt/Is+zVi3lrS6QnOTfsCTsBXCJ9K9BTWV9Ng4rJrzBcR4zOlI/VL4l4DNe8He9DT72Ug49EKDERa6gQcs=
