language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: 128technology
  password:
    secure: hyJxq1Y0zoVdwJJQdhw8LWmWt1l7xxgW1WyUlIo9dyYciewgskvZR6tE8L/F9iwMeZ3aISLr7KifAR6pQIC8mrcZ7YdVIArpwptfAJdJEvkf2+gVyu/6n/7epV8qRI0JoJD3D2+0ZRy+L2S19cHIrDayBaVaTCfOua8cy1Y4aFVxikzeFjs/WVL+cp0Mbup8rd8RXSoxrqW8oYAOH0clPPfVizbwDY7Whkhd+yAbtkdi7x8SAcClYzB7nHYecGQ3ifJTnGrqpKaxSniUa32CLhn91azws3Fglhn0RUqu6Oegr0Bz+ayV5fdWMo94d5xuuUmWcHWwMMmtTa5esOm6yEESSpjvNCUeu+T3gkqIhmfo63rmzkwwTwZRQMO77jgnat/RgWgs2EvlL/QG1yqMWHguvnHc/UajKPZbtgXdBgMjhfIGxs6G2gFLg+fPRNFWBKAdzyAN7CmG28dGkGDnyzoTsfs/lh6jdluCgE08TUajMxqUwJr3nx0Mwnc7oMLLOxk/5PSt34W1OeVsG2+Y8NF+qDEkUYqq6bSGIIWofRrYAYvo7RI5oVELeHca71ZB8YpeTYYD0fzEtSrWR//psdC+iPVttAkqltYTe0h7CUwjir/emDZiFav5zz4vqFWmg9lFWwJMJdr9BYexNglifuR1hdzNC2uOUeX2iaLHLns=
  distributions: sdist bdist_wheel --universal
  on:
    tags: true
