[tool.black]
line-length = 88

[tool.isort]
# See https://github.com/timothycrosley/isort/issues/694
# on how this configuration is valid with black.
line_length=88
multi_line_output=3
lines_after_imports=2
include_trailing_comma=true
combine_as_imports=true

default_section="THIRDPARTY"

known_first_party = [
    "yinsolidated",
]
